[package]
name = "rust_p2p_peer_discovery"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["full"] }
libp2p = { version = "0", features = [
    "tokio",
    "tcp",
    "mdns",
    "noise",
    "yamux",
] }
